#!/usr/bin/env node
/* tools/build-debug.mjs — generates dist/exsa.debug.css
   The markup-contract linter. Development only — never ship in production.
   Link AFTER exsa.css + components and enable with <html data-debug>:
   every component root missing one of its required parts gets a red dashed
   outline plus a label naming the missing part. Pure CSS — no JavaScript. */
import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');

export function generateDebugCss(manifestPath = join(root, 'manifest.json')) {
  const manifest = JSON.parse(readFileSync(manifestPath, 'utf8'));
  const head = `/* ════════════════════════════════════════════════════════════
   EXSA markup-contract linter — DEVELOPMENT ONLY.
   Link after exsa.css + your components. Enable: <html data-debug>
   A component root missing a required part gets a red dashed
   outline and a label naming the missing part. Pure CSS.
   Generated by tools/build-debug.mjs from manifest structure.
   ════════════════════════════════════════════════════════════ */

[data-debug] {
  --dbg-danger: var(--color-danger, #dc2626);
  --dbg-warn: var(--color-warning, #f59e0b);
}

[data-debug] [data-dbg-suggest]{
  outline: 2px dashed var(--dbg-warn);
  outline-offset: 2px;
  position: relative;
}

[data-debug] [data-dbg-suggest]::after{
  content: attr(data-dbg-suggest);
  position: absolute;
  top: -1.6em;
  inset-inline-start: 0;
  z-index: 9999;
  background: var(--dbg-warn);
  color: #111827;
  font-family: var(--font-family-mono, monospace);
  font-size: 11px;
  line-height: 1;
  padding: 4px 8px;
  border-radius: 4px;
  white-space: nowrap;
  pointer-events: none;
}

`;
  const rules = [];
  const emit = (scope, part) => {
    // one rule per required part — a scope missing ANY required part is flagged
    const sel = `[data-debug] ${scope}:not(:has(${part}))`;
    rules.push(`${sel}{
  outline: 2px dashed var(--dbg-danger);
  outline-offset: 2px;
  position: relative;
}`);
    rules.push(`${sel}::after{
  content: "missing ${part}";
  position: absolute;
  top: -1.6em;
  inset-inline-start: 0;
  z-index: 9999;
  background: var(--dbg-danger);
  color: #fff;
  font-family: var(--font-family-mono, monospace);
  font-size: 11px;
  line-height: 1;
  padding: 4px 8px;
  border-radius: 4px;
  white-space: nowrap;
  pointer-events: none;
}`);
  };
  for (const c of manifest.components) {
    const s = c.structure;
    if (!s || !s.required || !s.required.length) continue;
    for (const r of s.required) emit(s.root, r);
  }
  /* layouts: conditional contracts — a body mode class must contain its zones */
  for (const lay of manifest.layouts || []) {
    for (const cond of lay.structure || []) {
      for (const r of cond.required || []) emit(cond.when, r);
    }
  }
  return head + rules.join('\n') + '\n';
}

/* ---------- class registry (spellchecker) ---------- */
const CSS_SOURCES = (() => {
  const files = ['dist/exsa.css', 'dist/exsa.fluid.css'];
  for (const dir of ['dist/components', 'dist/layouts', 'dist/templates']) {
    const walk = (rel) => {
      for (const ent of readdirSync(join(root, rel), { withFileTypes: true })) {
        const p = `${rel}/${ent.name}`;
        if (ent.isDirectory()) walk(p);
        else if (ent.name.endsWith('.css')) files.push(p);
      }
    };
    walk(dir);
  }
  return files;
})();

function classRegistry() {
  const classes = new Set();
  for (const f of CSS_SOURCES) {
    const src = readFileSync(join(root, f), 'utf8').replace(/\/\*[\s\S]*?\*\//g, '');
    for (const m of src.matchAll(/\.([a-zA-Z_][a-zA-Z0-9_-]*)/g)) classes.add(m[1]);
  }
  return classes;
}

export function generateDebugJs() {
  const classes = classRegistry();
  const prefixes = new Set(['u']); // single-dash utility namespace handled specially
  for (const c of classes) {
    const m = /^([a-zA-Z][a-zA-Z0-9-]*?)(?:__|--)/.exec(c);
    if (m) prefixes.add(m[1]);
  }
  const payload = JSON.stringify({ classes: [...classes].sort(), prefixes: [...prefixes].sort() });
  return `/* ════════════════════════════════════════════════════════════
   EXSA class-name spellchecker — DEVELOPMENT ONLY.
   Load AFTER the debug stylesheet. Enable: <html data-debug>
   A class whose prefix is a known EXSA root but is not registered
   gets an amber outline + "did you mean?" label (Levenshtein).
   Opt a custom extension out per element: data-dbg-allow="card__cta"
   Generated by tools/build-debug.mjs from the dist CSS registry.
   ════════════════════════════════════════════════════════════ */
const EXSA_DEBUG_CLASSES = ${payload};

(function () {
  if (!document.documentElement.hasAttribute('data-debug')) return;

  var known = {};
  EXSA_DEBUG_CLASSES.classes.forEach(function (c) { known[c] = true; });
  var prefixes = {};
  EXSA_DEBUG_CLASSES.prefixes.forEach(function (p) { prefixes[p] = true; });

  function lev(a, b) {
    var m = a.length, n = b.length, i, j, p = [], c = [], t;
    if (!m) return n;
    if (!n) return m;
    for (i = 0; i <= n; i++) p[i] = i;
    for (i = 1; i <= m; i++) {
      c[0] = i;
      for (j = 1; j <= n; j++) {
        c[j] = Math.min(p[j] + 1, c[j - 1] + 1, p[j - 1] + (a[i - 1] === b[j - 1] ? 0 : 1));
      }
      t = p; p = c; c = t;
    }
    return p[n];
  }

  function analyze(cls) {
    var i = cls.indexOf('__');
    if (i > 0) return { p: cls.slice(0, i), sep: '__' };
    i = cls.indexOf('--');
    if (i > 0) return { p: cls.slice(0, i), sep: '--' };
    if (cls.indexOf('u-') === 0) return { p: 'u', sep: '-' };
    return null;
  }

  var reported = {};
  var logged = false;
  function check(cls) {
    if (known[cls] || reported[cls]) return null;
    var a = analyze(cls);
    if (!a || !prefixes[a.p]) return null;
    var head = a.p + a.sep;
    var rest = cls.slice(head.length);
    var best = null, bd = 9;
    EXSA_DEBUG_CLASSES.classes.forEach(function (c) {
      if (c.indexOf(head) !== 0 || c === cls) return;
      var d = lev(c.slice(head.length), rest);
      if (d < bd) { bd = d; best = c; }
    });
    var s = best && bd <= 2 ? best : null;
    reported[cls] = s;
    return { cls: cls, suggest: s };
  }

  function scan() {
    var els = document.querySelectorAll('[class]');
    for (var i = 0; i < els.length; i++) {
      var el = els[i];
      if (el.hasAttribute('data-dbg-suggest')) continue;
      var allow = el.getAttribute('data-dbg-allow') || '';
      var found = null;
      for (var k = 0; k < el.classList.length; k++) {
        var cls = el.classList[k];
        if (allow.split(' ').indexOf(cls) >= 0) continue;
        found = check(cls);
        if (found) break;
      }
      if (found) {
        el.setAttribute('data-dbg-suggest', found.cls + (found.suggest ? ' — did you mean ' + found.suggest + '?' : ' — not an EXSA class'));
      }
    }
    var bad = Object.keys(reported);
    if (bad.length && !logged) {
      logged = true;
      console.warn('EXSA debug — unknown classes: ' + bad.map(function (c) { return c + (reported[c] ? ' → ' + reported[c] : ''); }).join(', '));
    }
  }

  scan();
  window.addEventListener('load', scan);
  var t = null;
  new MutationObserver(function () {
    if (t) clearTimeout(t);
    t = setTimeout(scan, 250);
  }).observe(document.documentElement, { childList: true, subtree: true });
})();
`;
}

const out = generateDebugCss();
const outJs = generateDebugJs();
if (process.argv[1] && process.argv[1].endsWith('build-debug.mjs')) {
  writeFileSync(join(root, 'dist/exsa.debug.css'), out);
  writeFileSync(join(root, 'dist/exsa.debug.js'), outJs);
  const n = out.match(/outline: 2px dashed/g)?.length || 0;
  console.log(`✔ wrote dist/exsa.debug.css (${n} contract rules) + dist/exsa.debug.js (${classRegistry().size} registered classes)`);
}
