#!/usr/bin/env node
/* tools/build-debug.mjs — generates dist/exsa.debug.css
   The markup-contract linter. Development only — never ship in production.
   Link AFTER exsa.css + components and enable with <html data-debug>:
   every component root missing one of its required parts gets a red dashed
   outline plus a label naming the missing part. Pure CSS — no JavaScript. */
import { readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');

export function generateDebugCss(manifestPath = join(root, 'manifest.json')) {
  const manifest = JSON.parse(readFileSync(manifestPath, 'utf8'));
  const head = `/* ════════════════════════════════════════════════════════════
   EXSA markup-contract linter — DEVELOPMENT ONLY.
   Link after exsa.css + your components. Enable: <html data-debug>
   A component root missing a required part gets a red dashed
   outline and a label naming the missing part. Pure CSS.
   Generated by tools/build-debug.mjs from manifest structure.
   ════════════════════════════════════════════════════════════ */

[data-debug] {
  --dbg-danger: var(--color-danger, #dc2626);
}

`;
  const rules = [];
  for (const c of manifest.components) {
    const s = c.structure;
    if (!s || !s.required || !s.required.length) continue;
    const root = s.root;
    const missing = s.required.map((r) => `:not(:has(${r}))`).join('');
    rules.push(`[data-debug] ${root}${missing}{
  outline: 2px dashed var(--dbg-danger);
  outline-offset: 2px;
  position: relative;
}`);
    const label = s.required.length === 1
      ? `missing ${s.required[0]}`
      : 'missing required part(s)';
    rules.push(`[data-debug] ${root}${missing}::after{
  content: "${label}";
  position: absolute;
  top: -1.6em;
  inset-inline-start: 0;
  z-index: 9999;
  background: var(--dbg-danger);
  color: #fff;
  font-family: var(--font-family-mono, monospace);
  font-size: 11px;
  line-height: 1;
  padding: 4px 8px;
  border-radius: 4px;
  white-space: nowrap;
  pointer-events: none;
}`);
  }
  return head + rules.join('\n') + '\n';
}

const out = generateDebugCss();
if (process.argv[1] && process.argv[1].endsWith('build-debug.mjs')) {
  writeFileSync(join(root, 'dist/exsa.debug.css'), out);
  const n = out.match(/outline: 2px dashed/g)?.length || 0;
  console.log(`✔ wrote dist/exsa.debug.css (${n} contract rules)`);
}
