#!/usr/bin/env node
/* EXSA token export builder — tools/build-tokens.mjs
   Run:  node tools/build-tokens.mjs          → regenerates tokens.json
         node tools/build-tokens.mjs --check  → exit 1 if tokens.json is stale

   Single source of truth (Phase 5):
     - metadata (names, types, notes, curated values) lives in manifest.json → tokens
     - VALUES are parsed from the CSS files referenced by the catalog
       (dist/exsa.css for core + z-index, component/layout files for scoped tokens)
   tokens.json is generated output — never hand-edit it. */
import { readFileSync, writeFileSync, statSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { pathToFileURL } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');

/* ---------- value extraction from CSS ---------- */
const defsCache = new Map();
function defsOf(file) {
  if (!defsCache.has(file)) {
    const src = readFileSync(join(root, file), 'utf8');
    const map = {};
    const re = /--([a-z0-9-]+)\s*:\s*([^;]+);/g;
    let m;
    while ((m = re.exec(src))) if (!(m[1] in map)) map[m[1]] = m[2].trim();
    defsCache.set(file, map);
  }
  return defsCache.get(file);
}

const camel = (s) =>
  s.replace(/^--/, '')
    .split('-')
    .map((w, i) => (i ? w[0].toUpperCase() + w.slice(1) : w))
    .join('');
const lowerFirst = (s) => s[0].toLowerCase() + s.slice(1);
/* key derivation: camelCase minus the group word for color/zIndex groups */
const keyOf = (css, group) => {
  let k = camel(css);
  if (group === 'color' && k.startsWith('color')) k = lowerFirst(k.slice(5));
  if (group === 'zIndex' && k.startsWith('z')) k = lowerFirst(k.slice(1));
  return k;
};
const remToPx = (v) => {
  const m = v.match(/^([\d.]+)rem$/);
  return m ? Math.round(parseFloat(m[1]) * 16) : null;
};

function buildEntry(file, group, e) {
  const out = { name: e.name, css: e.css, type: e.type };
  if (e.fallback !== undefined) {
    out.fallback = e.fallback;
    if (e.note) out.note = e.note;
    return out;
  }
  const raw = defsOf(file)[e.css.slice(2)];
  if (raw === undefined) throw new Error(`${e.css}: no definition found in ${file} — run tools/build-tokens.mjs after defining it, or add "fallback"`);
  if (e.type === 'color') {
    const ld = raw.match(/^light-dark\(\s*(.+?)\s*,\s*(.+?)\s*\)$/);
    if (e.light !== undefined && e.dark !== undefined) {
      out.light = e.light;
      out.dark = e.dark;
    } else if (ld) {
      out.light = ld[1];
      out.dark = ld[2];
    } else {
      out.value = raw;
    }
  } else if (e.type === 'number' && group !== 'zIndex') {
    const n = parseFloat(raw);
    out.value = Number.isFinite(n) && /^-?[\d.]+$/.test(raw) ? n : raw;
  } else if (e.type === 'dimension') {
    out.value = raw;
    const px = remToPx(raw);
    if (px !== null) out.px = px;
  } else {
    out.value = raw;
  }
  if (e.note) out.note = e.note;
  if (e.unit) out.unit = e.unit;
  return out;
}

export function buildTokens() {
  const manifest = JSON.parse(readFileSync(join(root, 'manifest.json'), 'utf8'));
  const cat = manifest.tokens;
  if (!cat) throw new Error('manifest.json has no "tokens" section');

  const output = {
    framework: 'EXSA',
    version: manifest.version,
    description:
      'Design-token export: 76 core tokens (of the 94 defined in exsa.css) plus the z-index scale and component/layout tokens. Override any token in your theme file, or restyle every surface with a skin — all components update instantly. Generated by tools/build-tokens.mjs from manifest.json + the CSS files — do not edit by hand.',
    core: 'dist/exsa.css',
    size: Math.round(statSync(join(root, 'dist/exsa.css')).size / 1024) + ' KB',
    tokens: {},
    components: {},
    layouts: {},
    zIndex: {},
    exports: {
      css: 'Copy the :root block from exsa.css into your stylesheet.',
      js: "const tokens = { colorLink: '#118bee', gap: '1rem', ... };",
      figma: 'Import this JSON via a Figma plugin (e.g. Design Tokens, Tokens Studio).',
      tailwind: "module.exports = { theme: { extend: { colors: { exsa: { link: '#118bee', ... } } } } };"
    }
  };

  for (const [group, entries] of Object.entries(cat.core)) {
    if (group === 'zIndex') {
      for (const e of entries) output.zIndex[keyOf(e.css, 'zIndex')] = buildEntry('dist/exsa.css', 'zIndex', e);
    } else {
      const bucket = (output.tokens[group] = {});
      for (const e of entries) bucket[keyOf(e.css, group)] = buildEntry('dist/exsa.css', group, e);
    }
  }
  for (const [id, comp] of Object.entries(cat.components || {})) {
    const bucket = (output.components[id] = { file: comp.file, tokens: {} });
    for (const e of comp.tokens) bucket.tokens[keyOf(e.css, 'components')] = buildEntry(comp.file, 'components', e);
  }
  for (const [id, lay] of Object.entries(cat.layouts || {})) {
    const bucket = (output.layouts[id] = { file: lay.file, tokens: {} });
    for (const e of lay.tokens) bucket.tokens[keyOf(e.css, 'layouts')] = buildEntry(lay.file, 'layouts', e);
  }
  return output;
}

/* ---------- CLI ---------- */
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  const output = buildTokens();
  const json = JSON.stringify(output, null, 2) + '\n';
  if (process.argv.includes('--check')) {
    const current = readFileSync(join(root, 'tokens.json'), 'utf8');
    if (current !== json) {
      console.error('✗ tokens.json is out of date — run: node tools/build-tokens.mjs');
      process.exit(1);
    }
    console.log('✓ tokens.json is up to date');
  } else {
    writeFileSync(join(root, 'tokens.json'), json);
    console.log('✓ wrote tokens.json');
  }
}
